patch_matcher:

  feature_normalization:
    use_gaussian_norm: False # gaussian feature normalization
    scaling_norm: False # normalize features to length 1

  match:
    nn_threshold: 0.7 # threshold for nearest neighbour match

advanced_patch_matcher:

  patch_size: 7 # size of patch for feature extraction

  key_points_corner:
    n_max_points_template: 1800 # max key points to extract for template
    n_max_points_patch: 8 # max key points to extract for patch
    threshold_low: 0.00001 # lower threshold for response matrix
    nms_neighbourhood: 4 # local non maximum suppression neighbourhood

  key_points_edge:
    n_max_points_template: 200 # max key points to extract for template
    n_max_points_patch: 4 # max key points to extract for patch
    threshold_low: 0.000005 # lower threshold for response matrix
    threshold_high: 0.000007 # upper threshold for response matrix
    nms_neighbourhood: 8 # local non maximum suppression neighbourhood

  feature_extraction:
    use_3_channels: True # use all 3 channels for feature extraction
    gradient_histogram:
      num_angle_bins: 8 # number of angle bins used for gradient histogram
      weight_coefficient: 1 # weights use for bins in gradient histogram

  match:
    two_point_max_diff: 40 # maximum difference between 2 point to represent same patch
    filters:
      use_ransac_filter: True # use ransac filter to filter out outliers
