patch_matcher:
  match:
    nn_treshold: 0.7 # threshold for nearest neighbour match

    filters:
      use_match_median_filter: True # use median filter to filter matched outliers
      use_match_gauss_filter: True # use gaussian filter to filter outliers

advanced_patch_matcher:

  feature_extraction:

    use_3_channels: True # use all 3 channels for feature extraction
    3_channels:
      use_sum_feature: True # sum all features instead of concatenating them

    gradient_histogram:
      num_agnle_bins: 8 # number of angle bins used for gradient histogram


