patch_matcher:

  feature_normalization:
    use_gaussian_norm: False
    use_global_norm: False
    scaling_norm: False

  match:
    nn_threshold: 0.7 # threshold for nearest neighbour match

advanced_patch_matcher:

  patch_size: 7
  n_max_points_corners_template: 1800
  n_max_points_edges_template: 200
  n_max_points_corners_patch: 8
  n_max_points_edges_patch: 4

  feature_extraction:
    use_3_channels: True # use all 3 channels for feature extraction
    gradient_histogram:
      num_angle_bins: 8 # number of angle bins used for gradient histogram
      weight_coefficient: 1

  match:
    two_point_max_diff: 40
    filters:
      use_ransac_filter: True # use median filter to filter matched outliers
