patch_matcher:

  feature_normalization:
    use_gaussian_norm: True
    use_global_norm: True

  match:
    nn_threshold: 0.7 # threshold for nearest neighbour match

advanced_patch_matcher:

  feature_extraction:
    use_3_channels: True # use all 3 channels for feature extraction
    3_channels:
      use_sum_feature: True # sum all features instead of concatenating them
    gradient_histogram:
      num_angle_bins: 8 # number of angle bins used for gradient histogram

  match:
    filters:
      use_match_median_filter: True # use median filter to filter matched outliers
      use_match_gauss_filter: True # use gaussian filter to filter outliers
